<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6Xelxe8\AppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6Xelxe8/AppKernelProdContainer.php') {
    touch(__DIR__.'/Container6Xelxe8.legacy');

    return;
}

if (!\class_exists(AppKernelProdContainer::class, false)) {
    \class_alias(\Container6Xelxe8\AppKernelProdContainer::class, AppKernelProdContainer::class, false);
}

return new \Container6Xelxe8\AppKernelProdContainer([
    'container.build_hash' => '6Xelxe8',
    'container.build_id' => 'c0584b77',
    'container.build_time' => 1726097267,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6Xelxe8');
