<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOMMDuyx\AppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOMMDuyx/AppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerOMMDuyx.legacy');

    return;
}

if (!\class_exists(AppKernelProdContainer::class, false)) {
    \class_alias(\ContainerOMMDuyx\AppKernelProdContainer::class, AppKernelProdContainer::class, false);
}

return new \ContainerOMMDuyx\AppKernelProdContainer([
    'container.build_hash' => 'OMMDuyx',
    'container.build_id' => 'f3ae004c',
    'container.build_time' => 1726122938,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOMMDuyx');
