<?php

namespace Container6Xelxe8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_45UuruZService extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored.45UuruZ' shared service.
     *
     * @return \MauticPlugin\RandomSmtpBundle\Controller\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "MauticPlugin\\RandomSmtpBundle\\Controller\\SmtpController::indexAction()": the $request argument is type-hinted with the non-existent class or interface: "MauticPlugin\\RandomSmtpBundle\\Controller\\Request". Did you forget to add a use statement?');
    }
}
