<?php

namespace Container6Xelxe8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YQUgWrXService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.YQUgWrX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YQUgWrX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.45UuruZ', NULL, 'Cannot determine controller argument for "MauticPlugin\\RandomSmtpBundle\\Controller\\SmtpController::indexAction()": the $request argument is type-hinted with the non-existent class or interface: "MauticPlugin\\RandomSmtpBundle\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'request' => '?',
        ]);
    }
}
