<?php

namespace Container6Xelxe8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Plugin_Randomsmtp_Controller_SmtpService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.plugin.randomsmtp.controller.smtp' shared service.
     *
     * @return \MauticPlugin\RandomSmtpBundle\Controller\SmtpController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.plugin.randomsmtp.controller.smtp'] = new \MauticPlugin\RandomSmtpBundle\Controller\SmtpController(new \MauticPlugin\RandomSmtpBundle\Service\RandomSmtpService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), $container->getEnv('json:MAUTIC_SMTP_CONFIGS')));
    }
}
