<?php

namespace Container6Xelxe8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmtpControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\RandomSmtpBundle\Controller\SmtpController' shared autowired service.
     *
     * @return \MauticPlugin\RandomSmtpBundle\Controller\SmtpController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['MauticPlugin\\RandomSmtpBundle\\Controller\\SmtpController'] = $instance = new \MauticPlugin\RandomSmtpBundle\Controller\SmtpController(($container->services['MauticPlugin\\RandomSmtpBundle\\Service\\RandomSmtpService'] ?? ($container->services['MauticPlugin\\RandomSmtpBundle\\Service\\RandomSmtpService'] = new \MauticPlugin\RandomSmtpBundle\Service\RandomSmtpService())));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->get_ServiceLocator_Mx0UMmYService())->withContext('MauticPlugin\\RandomSmtpBundle\\Controller\\SmtpController', $container));

        return $instance;
    }
}
