<?php

namespace ContainerOMMDuyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRandomSmtpServiceService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\RandomSmtpBundle\Service\RandomSmtpService' shared autowired service.
     *
     * @return \MauticPlugin\RandomSmtpBundle\Service\RandomSmtpService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['MauticPlugin\\RandomSmtpBundle\\Service\\RandomSmtpService'] = new \MauticPlugin\RandomSmtpBundle\Service\RandomSmtpService();
    }
}
